__author__ = 'fandongyun'

#this script is created for un-gzip the log files, and save them to specified directories.
# #be careful to handle the filenames, since the logfiles generated by the servers in the same day  are the same.

import glob

#glob all the filenames in specific dir.

class TarGzFilesGlob():
    def __init__(self,dir):
        self.gz_file_dir = dir

    def find_all(self):
        import glob
        files = glob.glob(self.gz_file_dir)
        return files


def test_glob():
        files = TarGzFilesGlob(r"/Volumes/VMware Shared Folders/fandongyunWin7Share/Nginx data log/proxy001/*.tar.gz")\
            .find_all()
        print " files num: %s" % len(files)
        return files

def test_glob2():
        files = TarGzFilesGlob(r"/Volumes/VMware Shared Folders/fandongyunWin7Share/Nginx data log/proxy002/*.tar.gz")\
            .find_all()
        print " files num: %s" % len(files)
        return files

# /Volumes/VMware Shared Folders/fandongyunWin7Share/Nginx data log/p2
def test_glob3():
        files = TarGzFilesGlob(r"/Volumes/VMware Shared Folders/fandongyunWin7Share/Nginx data log/p2/*.tar.gz")\
            .find_all()
        print " files num: %s" % len(files)
        return files


if __name__ == "__main__":
    test_glob()

