__author__ = 'fandongyun'

#this script is created for un-gzip the log files, and save them to specified directories.
# #be careful to handle the filenames, since the logfiles generated by the servers in the same day  are the same.

import glob

#glob all the filenames in specific dir.
def find_all(dir_files_grep):
    import glob
    files = glob.glob(dir_files_grep)
    return files


def test_glob():
    files = find_all(r"/Volumes/VMware Shared Folders/fandongyunWin7Share/Nginx data log/proxy001/*.tar.gz")
    print " files num: %s" % len(files)
    return files


if __name__ == "__main__":
    test_glob()